[tool.mypy]
mypy_path = "stubs"
python_version = "3.13"

[tool.ruff]
line-length = 80
target-version = "py313"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D",
    "PLR0915",
    "PTH",
    "S603",
    "S607",
    "T201",
]

[tool.pip-tools]
generate-hashes = true
strip-extras = true
